version: '3'
services:
  trfm:
    image: hashicorp/terraform:1.1.5
    volumes:
      - .:/data
    working_dir: /data
    #environment:
    #- AWS_ACCESS_KEY_ID:${AWS_ACCESS_KEY_ID}
    #- AWS_SECRET_ACCESS_KEY:${AWS_SECRET_ACCESS_KEY}
    env_file:
      - .env

